import { Alert, Button, FileInput } from "flowbite-react";
import { useState } from "react";
import { importMultisigAddresses } from "./lib/multisig-address.js";
import { readAsText } from "./lib/file-upload.js";

const ERROR_MESSAGE = "Opps, error occurs when processing the uploaded file";

export default function NewAddressPage({ addAddress, navigate }) {
  const [state, setState] = useState({
    isProcessing: false,
    error: null,
  });

  const submit = async (e) => {
    e.preventDefault();
    setState({ isProcessing: true, error: null });

    try {
      const fileInput = document.getElementById("file-upload");
      const fileContent = await readAsText(fileInput.files[0]);
      const addresses = importMultisigAddresses(JSON.parse(fileContent));
      addAddress(addresses);
      navigate("#/");
    } catch (error) {
      setState({
        isProcessing: false,
        error: `${ERROR_MESSAGE}: ${error}`,
      });
    }
  };

  return (
    <form onSubmit={submit} className="flex flex-col gap-4">
      <h2 className="text-lg mb-4">Import Multisig Addresses</h2>
      {state.error ? (
        <Alert className="mb-4" color="failure">
          {state.error}
        </Alert>
      ) : null}

      <div>
        <p className="mb-0">Supported formats:</p>
        <ul className="mb-4 list-disc list-inside">
          <li>
            The JSON file generated by <code>ckb-cli tx init</code>
          </li>
          <li>
            The JSON file exported from Neuron via the Multisig Address Tool in
            the Tools menu.
          </li>
        </ul>
        <FileInput id="file-upload" name="file-upload" required />
      </div>

      <Button
        isProcessing={state.isProcessing}
        disabled={state.isProcessing}
        type="submit"
      >
        Upload
      </Button>
    </form>
  );
}
