import { Button, FileInput } from "flowbite-react";

export default function ImportTransactionPage() {
  const submit = () => {
    console.log("submit");
  };

  return (
    <form onSubmit={submit} className="flex flex-col gap-4">
      <h2 className="text-lg mb-4">Import Transaction</h2>

      <p>
        Import a new transaction. If the transaction exists, any new signatures
        found in the uploaded file will be merged into the existing transaction.
      </p>

      <div>
        <p className="mb-0">Supported formats:</p>
        <ul className="mb-4 list-disc list-inside">
          <li>The Building Packet JSON file exported in this web app.</li>
          <li>
            The JSON file generated by <code>ckb-cli tx init</code>
          </li>
          <li>
            The JSON file exported from Neuron when sending CKB from a multisig
            address via the Multisig Address Tool in the Tools menu.
          </li>
        </ul>
        <FileInput id="file-upload" name="file-upload" required />
      </div>
    </form>
  );
}
